### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by jenslind** [boxen/puppet-mongodb#23] opened 2015-04-26 12:36 UTC
I am unable to build mongodb on 10.10.3 with latest CLT installed (6.3.1).
Seems to be this issue: https://jira.mongodb.org/browse/SERVER-15182
Probably the clang version that has been updated on the latest CLT.

I am able to install mongodb 3.x without issues.
Probably need to update the mongodb version?

**Comment by jenslind** [comment] 2015-04-26 19:51
Made an pull-request, not sure if this is the way to go though!

https://github.com/boxen/puppet-mongodb/pull/24

**Comment by dannyfallon** [comment] 2015-04-27 10:22
The problem is with Clang v3.5+ on Yosemite with MongoDB 2.6.x/2.4.x. I opened up a ticket with MongoDB and backported the same fixes they applied to 3.0 in https://github.com/mongodb/mongo/pull/956 but they closed it. Like it says in that ticket, the proper fix is to just use the `--disable-warnings-as-errors` build flag.

**Comment by jenslind** [comment] 2015-04-27 10:52
Yeah you are probably right about adding the `--disable-warnings-as-errors` flag to fix this for now. However, if upgrading to 3.0.2 we get rid of some patches which is needed now to add yosemite support.
And yes it would be great to be able to pick a specific version! :)

**Comment by dannyfallon** [comment] 2015-04-27 10:57
Yep, there are benefits to being on the latest and greatest versions. As a 2.6 user for which this module is currently broken for I'd really like it fixed for 2.6 first before an upgrade to 3.0 so I don't have to fork and do the fix myself :smile: 

I think those patches are not needed if you update to 2.6.9 (the latest stable 2.6 release). I know that the only modification I had to make to MongoDB source to build is the addition on the flag I mentioned. I'll submit a PR adding the flag, a separate one to upgrade to 2.6.9 and we'll let the maintainers decide the merge order

**Comment by jenslind** [comment] 2015-04-27 11:00
Sounds good! :+1:

**Closed** 2015-05-04 01:21 UTC
